version: '3.8'

services:
  backend:
    image: dipamj/modernnodeodm-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydb

  frontend:
    image: dipamj/modernnodeodm-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: dipamj/modernnodeodm-db:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
