services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - DB_HOST=host.docker.internal  # Points to the host machine
      - DB_USER=root
      - DB_PASSWORD=Winter.123
      - DB_NAME=mydb
      - DB_PORT=3306
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend